-- Up
CREATE TABLE User (
    userid   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT    NOT NULL UNIQUE,
    password TEXT    NOT NULL,
    salt     TEXT    NOT NULL UNIQUE
);

CREATE TABLE List (
    listid  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    listname TEXT NOT NULL,
    userid INTEGER NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY(userid) REFERENCES User(userid)
);

CREATE TABLE Item (
    itemid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    itemname TEXT NOT NULL,
    orderInList INTEGER NOT NULL,
    url TEXT,
    listid INTEGER NOT NULL,
    FOREIGN KEY(listid) REFERENCES List(listid)
);

-- Down
DROP TABLE User;
DROP TABLE List;
DROP TABLE Item;